function out = intervention (st)
xp = linspace(st.minX, st.maxX, st.numPoints);
x = st.X;
y = st.Y;
pow = st.Power;
yint = interp1(x, y, xp);
ysp = spline(x, y, xp);
ypolyfit = polyfit(x, y, pow);
ypolyval = polyval(ypolyfit, xp);
sstot = (y - mean(y)).^2;
den = sum(sstot)./length(sstot);
ssint = (yint - mean(y)).^2;
sssp = (ysp - mean(y)).^2;
sspol = (ypolyval - mean(y)).^2;
rInt = sum(ssint)./length(ssint)./den;
rSp = sum(sssp)./length(sssp)./den;
rPol = sum(sspol)./length(sspol)./den;
subplot(1,3,1);
hold on;
plot(x,y, 'b*');
plot(xp, yint, 'g+');
title(['Interp1: R^2 = ' sprintf('%.4f', rInt)]);
xlabel('x-axis');
ylabel('y-axis');
hold off;
subplot(1,3,2);
hold on;
plot(x,y, 'b*');
plot(xp, ysp, 'g+');
title(['Spline: R^2 = ' sprintf('%.4f', rSp)]);
xlabel('x-axis');
ylabel('y-axis');
hold off;
subplot(1,3,3);
hold on;
plot(x,y, 'b*');
plot(xp, ypolyval, 'g+');
title(['Polyfit/Polyval: R^2 = ' sprintf('%.4f', rPol)]);
xlabel('x-axis');
ylabel('y-axis');
hold off;
out = [round(rInt, 4), round(rSp, 4), round(rPol, 4)];
end